version: "3"
services:
  api:
    image: nonny898/pdf-to-text:lastest
    ports:
      - "3001:3001"
    networks:
      - backend
    environment:
      - MINIO_HOST=minio
      - REDIS_HOST=redis
    depends_on:
      - minio
      - redis

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    volumes:
      - data:/data
    networks:
      - backend
    command: server /data

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:

volumes:
  data:
